/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const VideoStatus = IDL.Variant({
  'live' : IDL.Null,
  'uploading' : IDL.Null,
  'processing' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ThumbnailType = IDL.Variant({
  'custom' : IDL.Null,
  'automatic' : IDL.Null,
});
export const VideoMetadata = IDL.Record({
  'id' : IDL.Text,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'thumbnailType' : IDL.Opt(ThumbnailType),
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'uploader' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'videoId' : IDL.Text,
});
export const FreePlanDetails = IDL.Record({
  'isActive' : IDL.Bool,
  'uploadsRemaining' : IDL.Nat,
});
export const StripeConfigAndUrls = IDL.Record({
  'proPlanUrl' : IDL.Opt(IDL.Text),
  'basicPlanUrl' : IDL.Opt(IDL.Text),
  'secretKey' : IDL.Opt(IDL.Text),
  'creatorPlanUrl' : IDL.Opt(IDL.Text),
  'subscriptionsEnabled' : IDL.Bool,
  'defaultPricing' : IDL.Opt(IDL.Nat),
  'publishableKey' : IDL.Opt(IDL.Text),
});
export const ModerationResult = IDL.Record({
  'allowed' : IDL.Bool,
  'matchedWords' : IDL.Vec(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAdminPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getBannedWords' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBlockedVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getFeaturedVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getFreePlanStatus' : IDL.Func([], [FreePlanDetails], ['query']),
  'getFullStripeConfigAndUrls' : IDL.Func([], [StripeConfigAndUrls], ['query']),
  'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getModerationResult' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ModerationResult)],
      ['query'],
    ),
  'getPermanentAdminPrincipal' : IDL.Func(
      [],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getPublicStripeConfigAndUrls' : IDL.Func(
      [],
      [StripeConfigAndUrls],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(VideoMetadata)], ['query']),
  'getVideoProgress' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getVideosByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isVideoAllowed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'overrideModerationStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'rerunModeration' : IDL.Func([IDL.Text], [], []),
  'rerunModerationAll' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVideoProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
  'searchVideosByCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'setBannedWords' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setFeaturedStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'storePermanentAdminPrincipal' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlikeVideo' : IDL.Func([IDL.Text], [], []),
  'updateStripeConfigAndUrls' : IDL.Func([StripeConfigAndUrls], [], []),
  'updateThumbnail' : IDL.Func([IDL.Text, ExternalBlob, ThumbnailType], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ThumbnailType),
      ],
      [],
      [],
    ),
  'verifyAdminAccess' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const VideoStatus = IDL.Variant({
    'live' : IDL.Null,
    'uploading' : IDL.Null,
    'processing' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ThumbnailType = IDL.Variant({
    'custom' : IDL.Null,
    'automatic' : IDL.Null,
  });
  const VideoMetadata = IDL.Record({
    'id' : IDL.Text,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'thumbnailType' : IDL.Opt(ThumbnailType),
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'uploader' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'videoId' : IDL.Text,
  });
  const FreePlanDetails = IDL.Record({
    'isActive' : IDL.Bool,
    'uploadsRemaining' : IDL.Nat,
  });
  const StripeConfigAndUrls = IDL.Record({
    'proPlanUrl' : IDL.Opt(IDL.Text),
    'basicPlanUrl' : IDL.Opt(IDL.Text),
    'secretKey' : IDL.Opt(IDL.Text),
    'creatorPlanUrl' : IDL.Opt(IDL.Text),
    'subscriptionsEnabled' : IDL.Bool,
    'defaultPricing' : IDL.Opt(IDL.Nat),
    'publishableKey' : IDL.Opt(IDL.Text),
  });
  const ModerationResult = IDL.Record({
    'allowed' : IDL.Bool,
    'matchedWords' : IDL.Vec(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAdminPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getBannedWords' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBlockedVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getFeaturedVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getFreePlanStatus' : IDL.Func([], [FreePlanDetails], ['query']),
    'getFullStripeConfigAndUrls' : IDL.Func(
        [],
        [StripeConfigAndUrls],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getModerationResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ModerationResult)],
        ['query'],
      ),
    'getPermanentAdminPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getPublicStripeConfigAndUrls' : IDL.Func(
        [],
        [StripeConfigAndUrls],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(VideoMetadata)], ['query']),
    'getVideoProgress' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getVideosByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isVideoAllowed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'overrideModerationStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'rerunModeration' : IDL.Func([IDL.Text], [], []),
    'rerunModerationAll' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVideoProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
    'searchVideosByCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'setBannedWords' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setFeaturedStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'storePermanentAdminPrincipal' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlikeVideo' : IDL.Func([IDL.Text], [], []),
    'updateStripeConfigAndUrls' : IDL.Func([StripeConfigAndUrls], [], []),
    'updateThumbnail' : IDL.Func(
        [IDL.Text, ExternalBlob, ThumbnailType],
        [],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ThumbnailType),
        ],
        [],
        [],
      ),
    'verifyAdminAccess' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };