/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : string,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'videoId' : string,
}
export type ExternalBlob = Uint8Array;
export interface FreePlanDetails {
  'isActive' : boolean,
  'uploadsRemaining' : bigint,
}
export interface ModerationResult {
  'allowed' : boolean,
  'matchedWords' : Array<string>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfigAndUrls {
  'proPlanUrl' : [] | [string],
  'basicPlanUrl' : [] | [string],
  'secretKey' : [] | [string],
  'creatorPlanUrl' : [] | [string],
  'subscriptionsEnabled' : boolean,
  'defaultPricing' : [] | [bigint],
  'publishableKey' : [] | [string],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type ThumbnailType = { 'custom' : null } |
  { 'automatic' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoMetadata {
  'id' : string,
  'status' : VideoStatus,
  'title' : string,
  'likeCount' : bigint,
  'thumbnail' : [] | [ExternalBlob],
  'blob' : ExternalBlob,
  'description' : string,
  'isFeatured' : boolean,
  'thumbnailType' : [] | [ThumbnailType],
  'timestamp' : bigint,
  'category' : string,
  'uploader' : Principal,
}
export type VideoStatus = { 'live' : null } |
  { 'uploading' : null } |
  { 'processing' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAdminPrincipalId' : ActorMethod<[], string>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getBannedWords' : ActorMethod<[], Array<string>>,
  'getBlockedVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getFeaturedVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getFreePlanStatus' : ActorMethod<[], FreePlanDetails>,
  'getFullStripeConfigAndUrls' : ActorMethod<[], StripeConfigAndUrls>,
  'getLikeCount' : ActorMethod<[string], bigint>,
  'getModerationResult' : ActorMethod<[string], [] | [ModerationResult]>,
  'getPermanentAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getPublicStripeConfigAndUrls' : ActorMethod<[], StripeConfigAndUrls>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getVideo' : ActorMethod<[string], [] | [VideoMetadata]>,
  'getVideoProgress' : ActorMethod<[string], bigint>,
  'getVideosByCategory' : ActorMethod<[string], Array<VideoMetadata>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isVideoAllowed' : ActorMethod<[string], boolean>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'overrideModerationStatus' : ActorMethod<[string, boolean], undefined>,
  'rerunModeration' : ActorMethod<[string], undefined>,
  'rerunModerationAll' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveVideoProgress' : ActorMethod<[string, bigint], undefined>,
  'searchVideos' : ActorMethod<[string], Array<VideoMetadata>>,
  'searchVideosByCategory' : ActorMethod<
    [string, string],
    Array<VideoMetadata>
  >,
  'setBannedWords' : ActorMethod<[Array<string>], undefined>,
  'setFeaturedStatus' : ActorMethod<[string, boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'storePermanentAdminPrincipal' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlikeVideo' : ActorMethod<[string], undefined>,
  'updateStripeConfigAndUrls' : ActorMethod<[StripeConfigAndUrls], undefined>,
  'updateThumbnail' : ActorMethod<
    [string, ExternalBlob, ThumbnailType],
    undefined
  >,
  'uploadVideo' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      ExternalBlob,
      [] | [ExternalBlob],
      [] | [ThumbnailType],
    ],
    undefined
  >,
  'verifyAdminAccess' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];