/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface StripeConfigAndUrls {
    proPlanUrl?: string;
    basicPlanUrl?: string;
    secretKey?: string;
    creatorPlanUrl?: string;
    subscriptionsEnabled: boolean;
    defaultPricing?: bigint;
    publishableKey?: string;
}
export interface FreePlanDetails {
    isActive: boolean;
    uploadsRemaining: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Comment {
    id: string;
    text: string;
    author: Principal;
    timestamp: bigint;
    videoId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ModerationResult {
    allowed: boolean;
    matchedWords: Array<string>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface VideoMetadata {
    id: string;
    status: VideoStatus;
    title: string;
    likeCount: bigint;
    thumbnail?: ExternalBlob;
    blob: ExternalBlob;
    description: string;
    isFeatured: boolean;
    thumbnailType?: ThumbnailType;
    timestamp: bigint;
    category: string;
    uploader: Principal;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ThumbnailType {
    custom = "custom",
    automatic = "automatic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoStatus {
    live = "live",
    uploading = "uploading",
    processing = "processing"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addComment(videoId: string, text: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteComment(videoId: string, commentId: string): Promise<void>;
    deleteVideo(videoId: string): Promise<void>;
    getAdminPrincipalId(): Promise<string>;
    getAllCategories(): Promise<Array<string>>;
    getAllVideos(): Promise<Array<VideoMetadata>>;
    getBannedWords(): Promise<Array<string>>;
    getBlockedVideos(): Promise<Array<VideoMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(videoId: string): Promise<Array<Comment>>;
    getFeaturedVideos(): Promise<Array<VideoMetadata>>;
    getFreePlanStatus(): Promise<FreePlanDetails>;
    getFullStripeConfigAndUrls(): Promise<StripeConfigAndUrls>;
    getLikeCount(videoId: string): Promise<bigint>;
    getModerationResult(videoId: string): Promise<ModerationResult | null>;
    getPermanentAdminPrincipal(): Promise<Principal | null>;
    getPublicStripeConfigAndUrls(): Promise<StripeConfigAndUrls>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserVideos(): Promise<Array<VideoMetadata>>;
    getVideo(id: string): Promise<VideoMetadata | null>;
    getVideoProgress(videoId: string): Promise<bigint>;
    getVideosByCategory(category: string): Promise<Array<VideoMetadata>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isVideoAllowed(videoId: string): Promise<boolean>;
    likeVideo(videoId: string): Promise<void>;
    overrideModerationStatus(videoId: string, allowed: boolean): Promise<void>;
    rerunModeration(videoId: string): Promise<void>;
    rerunModerationAll(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveVideoProgress(videoId: string, progressInSeconds: bigint): Promise<void>;
    searchVideos(searchQuery: string): Promise<Array<VideoMetadata>>;
    searchVideosByCategory(searchQuery: string, category: string): Promise<Array<VideoMetadata>>;
    setBannedWords(words: Array<string>): Promise<void>;
    setFeaturedStatus(videoId: string, isFeatured: boolean): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    storePermanentAdminPrincipal(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unlikeVideo(videoId: string): Promise<void>;
    updateStripeConfigAndUrls(config: StripeConfigAndUrls): Promise<void>;
    updateThumbnail(videoId: string, thumbnail: ExternalBlob, thumbnailType: ThumbnailType): Promise<void>;
    uploadVideo(id: string, title: string, description: string, category: string, blob: ExternalBlob, thumbnail: ExternalBlob | null, thumbnailType: ThumbnailType | null): Promise<void>;
    verifyAdminAccess(): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, ModerationResult as _ModerationResult, StripeConfigAndUrls as _StripeConfigAndUrls, StripeSessionStatus as _StripeSessionStatus, ThumbnailType as _ThumbnailType, UserProfile as _UserProfile, UserRole as _UserRole, VideoMetadata as _VideoMetadata, VideoStatus as _VideoStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getAdminPrincipalId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipalId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipalId();
            return result;
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBannedWords(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannedWords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannedWords();
            return result;
        }
    }
    async getBlockedVideos(): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedVideos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedVideos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getFeaturedVideos(): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedVideos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedVideos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFreePlanStatus(): Promise<FreePlanDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreePlanStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreePlanStatus();
            return result;
        }
    }
    async getFullStripeConfigAndUrls(): Promise<StripeConfigAndUrls> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullStripeConfigAndUrls();
                return from_candid_StripeConfigAndUrls_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullStripeConfigAndUrls();
            return from_candid_StripeConfigAndUrls_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCount(arg0);
            return result;
        }
    }
    async getModerationResult(arg0: string): Promise<ModerationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModerationResult(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModerationResult(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPermanentAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPermanentAdminPrincipal();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPermanentAdminPrincipal();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicStripeConfigAndUrls(): Promise<StripeConfigAndUrls> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicStripeConfigAndUrls();
                return from_candid_StripeConfigAndUrls_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicStripeConfigAndUrls();
            return from_candid_StripeConfigAndUrls_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserVideos(): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserVideos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserVideos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: string): Promise<VideoMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoProgress(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoProgress(arg0);
            return result;
        }
    }
    async getVideosByCategory(arg0: string): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isVideoAllowed(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVideoAllowed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVideoAllowed(arg0);
            return result;
        }
    }
    async likeVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeVideo(arg0);
            return result;
        }
    }
    async overrideModerationStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.overrideModerationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.overrideModerationStatus(arg0, arg1);
            return result;
        }
    }
    async rerunModeration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rerunModeration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rerunModeration(arg0);
            return result;
        }
    }
    async rerunModerationAll(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rerunModerationAll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rerunModerationAll();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveVideoProgress(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVideoProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVideoProgress(arg0, arg1);
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchVideosByCategory(arg0: string, arg1: string): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideosByCategory(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideosByCategory(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setBannedWords(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBannedWords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBannedWords(arg0);
            return result;
        }
    }
    async setFeaturedStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeaturedStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeaturedStatus(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async storePermanentAdminPrincipal(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storePermanentAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePermanentAdminPrincipal();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unlikeVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeVideo(arg0);
            return result;
        }
    }
    async updateStripeConfigAndUrls(arg0: StripeConfigAndUrls): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStripeConfigAndUrls(to_candid_StripeConfigAndUrls_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStripeConfigAndUrls(to_candid_StripeConfigAndUrls_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateThumbnail(arg0: string, arg1: ExternalBlob, arg2: ThumbnailType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateThumbnail(arg0, await to_candid_ExternalBlob_n34(this._uploadFile, this._downloadFile, arg1), to_candid_ThumbnailType_n35(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateThumbnail(arg0, await to_candid_ExternalBlob_n34(this._uploadFile, this._downloadFile, arg1), to_candid_ThumbnailType_n35(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadVideo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob, arg5: ExternalBlob | null, arg6: ThumbnailType | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n34(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n34(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async verifyAdminAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminAccess();
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_StripeConfigAndUrls_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeConfigAndUrls): StripeConfigAndUrls {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ThumbnailType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThumbnailType): ThumbnailType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoMetadata_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): Promise<VideoMetadata> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ThumbnailType]): ThumbnailType | null {
    return value.length === 0 ? null : from_candid_ThumbnailType_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ModerationResult]): ModerationResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoMetadata]): Promise<VideoMetadata | null> {
    return value.length === 0 ? null : await from_candid_VideoMetadata_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _VideoStatus;
    title: string;
    likeCount: bigint;
    thumbnail: [] | [_ExternalBlob];
    blob: _ExternalBlob;
    description: string;
    isFeatured: boolean;
    thumbnailType: [] | [_ThumbnailType];
    timestamp: bigint;
    category: string;
    uploader: Principal;
}): Promise<{
    id: string;
    status: VideoStatus;
    title: string;
    likeCount: bigint;
    thumbnail?: ExternalBlob;
    blob: ExternalBlob;
    description: string;
    isFeatured: boolean;
    thumbnailType?: ThumbnailType;
    timestamp: bigint;
    category: string;
    uploader: Principal;
}> {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        likeCount: value.likeCount,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.thumbnail)),
        blob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        isFeatured: value.isFeatured,
        thumbnailType: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.thumbnailType)),
        timestamp: value.timestamp,
        category: value.category,
        uploader: value.uploader
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proPlanUrl: [] | [string];
    basicPlanUrl: [] | [string];
    secretKey: [] | [string];
    creatorPlanUrl: [] | [string];
    subscriptionsEnabled: boolean;
    defaultPricing: [] | [bigint];
    publishableKey: [] | [string];
}): {
    proPlanUrl?: string;
    basicPlanUrl?: string;
    secretKey?: string;
    creatorPlanUrl?: string;
    subscriptionsEnabled: boolean;
    defaultPricing?: bigint;
    publishableKey?: string;
} {
    return {
        proPlanUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.proPlanUrl)),
        basicPlanUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.basicPlanUrl)),
        secretKey: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.secretKey)),
        creatorPlanUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.creatorPlanUrl)),
        subscriptionsEnabled: value.subscriptionsEnabled,
        defaultPricing: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.defaultPricing)),
        publishableKey: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.publishableKey))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    live: null;
} | {
    uploading: null;
} | {
    processing: null;
}): VideoStatus {
    return "live" in value ? VideoStatus.live : "uploading" in value ? VideoStatus.uploading : "processing" in value ? VideoStatus.processing : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    automatic: null;
}): ThumbnailType {
    return "custom" in value ? ThumbnailType.custom : "automatic" in value ? ThumbnailType.automatic : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n30(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoMetadata>): Promise<Array<VideoMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoMetadata_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_StripeConfigAndUrls_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripeConfigAndUrls): _StripeConfigAndUrls {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ThumbnailType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThumbnailType): _ThumbnailType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThumbnailType | null): [] | [_ThumbnailType] {
    return value === null ? candid_none() : candid_some(to_candid_ThumbnailType_n35(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proPlanUrl?: string;
    basicPlanUrl?: string;
    secretKey?: string;
    creatorPlanUrl?: string;
    subscriptionsEnabled: boolean;
    defaultPricing?: bigint;
    publishableKey?: string;
}): {
    proPlanUrl: [] | [string];
    basicPlanUrl: [] | [string];
    secretKey: [] | [string];
    creatorPlanUrl: [] | [string];
    subscriptionsEnabled: boolean;
    defaultPricing: [] | [bigint];
    publishableKey: [] | [string];
} {
    return {
        proPlanUrl: value.proPlanUrl ? candid_some(value.proPlanUrl) : candid_none(),
        basicPlanUrl: value.basicPlanUrl ? candid_some(value.basicPlanUrl) : candid_none(),
        secretKey: value.secretKey ? candid_some(value.secretKey) : candid_none(),
        creatorPlanUrl: value.creatorPlanUrl ? candid_some(value.creatorPlanUrl) : candid_none(),
        subscriptionsEnabled: value.subscriptionsEnabled,
        defaultPricing: value.defaultPricing ? candid_some(value.defaultPricing) : candid_none(),
        publishableKey: value.publishableKey ? candid_some(value.publishableKey) : candid_none()
    };
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThumbnailType): {
    custom: null;
} | {
    automatic: null;
} {
    return value == ThumbnailType.custom ? {
        custom: null
    } : value == ThumbnailType.automatic ? {
        automatic: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
